# lamin-IsceI0-CED5-WT
CRISPResso -r1 /home/gaolab/Downloads/sequences/lamin-IsceI-CED5-LDL11905_L1_1.fq.gz \
-r2 /home/gaolab/Downloads/sequences/lamin-IsceI-CED5-LDL11905_L1_2.fq.gz \
-a GCGTCGGTGACTCAGTGTTCGCGGGAGCGCCGCACCTACACCAGCCAACCCAGATCCCGAGGTCCGACAGCGCCCGGCCCAGATCCCCACGCCTGCCAGGAGCAAGCCGAGAGCCAGCCGGCCGGCGCACTCCGACTCCGAGCAGTCTCTGTCCTTCGACCCGAGCCCCGCGCCCTTTCCGGGACCCCTGCCCCGCGGGCAGCGCTGCCAACCTGCCGGCCATGGAGACCCCGTCCCAGCGGCGCGCCACCCGCAGCGGGGCGCAGGCCAGCTCCACTCCGCTGTCGCCCACCCGCATCACCCGGCTGCAGGAGAAGGAGGACCTGCAGGAGCTCAATGATCGCTTGGCGGTCTACATCGACCGTGTGCGCTCGCTGGAAACGGAGAACGCAGGGCTGCGCCTTCGCATCACCGAGTCTGAAGAGGTGGTCAGCCGCGAGGTGTCCGGCATCAAGGCCGCCTACGAG -g CCATGGAGACCCCGTCCCAG \
--name lamin-IsceI0-CED5-WT --output_folder /home/gaolab/Downloads/sequences/ --write_cleaned_report \
--place_report_in_output_folder --plot_window_size 20 -w 10 -wc -3

# lamin-IsceI0-CED5-corrected
CRISPResso -r1 /home/gaolab/Downloads/sequences/lamin-IsceI-CED5-LDL11905_L1_1.fq.gz \
-r2 /home/gaolab/Downloads/sequences/lamin-IsceI-CED5-LDL11905_L1_2.fq.gz \
-a GCGTCGGTGACTCAGTGTTCGCGGGAGCGCCGCACCTACACCAGCCAACCCAGATCCCGAGGTCCGACAGCGCCCGGCCCAGATCCCCACGCCTGCCAGGAGCAAGCCGAGAGCCAGCCGGCCGGCGCACTCCGACTCCGAGCAGTCTCTGTCCTTCGACCCGAGCCCCGCGCCCTTTCCGGGACCCCTGCCCCGCGGGCAGCGCTGCCAACCTGCCGGCCATGGAGACCCCGTCCATTACCCTGTTATCCCTACAGCGGCGCGCCACCCGCAGCGGGGCGCAGGCCAGCTCCACTCCGCTGTCGCCCACCCGCATCACCCGGCTGCAGGAGAAGGAGGACCTGCAGGAGCTCAATGATCGCTTGGCGGTCTACATCGACCGTGTGCGCTCGCTGGAAACGGAGAACGCAGGGCTGCGCCTTCGCATCACCGAGTCTGAAGAGGTGGTCAGCCGCGAGGTGTCCGGCATCAAGGCCGCCTACGAG -g CCATGGAGACCCCGTCCATTACCCTGTTATCCCTACAG \
--name lamin-IsceI0-CED5-corrected --output_folder /home/gaolab/Downloads/sequences/ --write_cleaned_report \
--place_report_in_output_folder --plot_window_size 20 -w 24 -wc -3

# lamin-IsceI0-TED6-WT
CRISPResso -r1 /home/gaolab/Downloads/sequences/lamin-IsceI-TED6-LDL11906_L1_1.fq.gz \
-r2 /home/gaolab/Downloads/sequences/lamin-IsceI-TED6-LDL11906_L1_2.fq.gz \
-a GCGTCGGTGACTCAGTGTTCGCGGGAGCGCCGCACCTACACCAGCCAACCCAGATCCCGAGGTCCGACAGCGCCCGGCCCAGATCCCCACGCCTGCCAGGAGCAAGCCGAGAGCCAGCCGGCCGGCGCACTCCGACTCCGAGCAGTCTCTGTCCTTCGACCCGAGCCCCGCGCCCTTTCCGGGACCCCTGCCCCGCGGGCAGCGCTGCCAACCTGCCGGCCATGGAGACCCCGTCCCAGCGGCGCGCCACCCGCAGCGGGGCGCAGGCCAGCTCCACTCCGCTGTCGCCCACCCGCATCACCCGGCTGCAGGAGAAGGAGGACCTGCAGGAGCTCAATGATCGCTTGGCGGTCTACATCGACCGTGTGCGCTCGCTGGAAACGGAGAACGCAGGGCTGCGCCTTCGCATCACCGAGTCTGAAGAGGTGGTCAGCCGCGAGGTGTCCGGCATCAAGGCCGCCTACGAG -g CCATGGAGACCCCGTCCCAG \
--name lamin-IsceI0-TED6-WT --output_folder /home/gaolab/Downloads/sequences/ --write_cleaned_report \
--place_report_in_output_folder --plot_window_size 20 -w 10 -wc -3

# lamin-IsceI0-TED6-corrected
CRISPResso -r1 /home/gaolab/Downloads/sequences/lamin-IsceI-TED6-LDL11906_L1_1.fq.gz \
-r2 /home/gaolab/Downloads/sequences/lamin-IsceI-TED6-LDL11906_L1_2.fq.gz \
-a GCGTCGGTGACTCAGTGTTCGCGGGAGCGCCGCACCTACACCAGCCAACCCAGATCCCGAGGTCCGACAGCGCCCGGCCCAGATCCCCACGCCTGCCAGGAGCAAGCCGAGAGCCAGCCGGCCGGCGCACTCCGACTCCGAGCAGTCTCTGTCCTTCGACCCGAGCCCCGCGCCCTTTCCGGGACCCCTGCCCCGCGGGCAGCGCTGCCAACCTGCCGGCCATGGAGACCCCGTCCATTACCCTGTTATCCCTACAGCGGCGCGCCACCCGCAGCGGGGCGCAGGCCAGCTCCACTCCGCTGTCGCCCACCCGCATCACCCGGCTGCAGGAGAAGGAGGACCTGCAGGAGCTCAATGATCGCTTGGCGGTCTACATCGACCGTGTGCGCTCGCTGGAAACGGAGAACGCAGGGCTGCGCCTTCGCATCACCGAGTCTGAAGAGGTGGTCAGCCGCGAGGTGTCCGGCATCAAGGCCGCCTACGAG -g CCATGGAGACCCCGTCCATTACCCTGTTATCCCTACAG \
--name lamin-IsceI0-TED6-corrected --output_folder /home/gaolab/Downloads/sequences/ --write_cleaned_report \
--place_report_in_output_folder --plot_window_size 20 -w 24 -wc -3

# mcherry-TED-WT
CRISPResso -r1 /home/gaolab/Downloads/sequences/mcherry-TED-LDL11903_L1_1.fq.gz \
-r2 /home/gaolab/Downloads/sequences/mcherry-TED-LDL11903_L1_2.fq.gz \
-a GGACATCACCTCCCACAACGAGGACTACACCATCGTGGAACAGTACGAACGCGCCGAGGGCCGCCACTCCACCGGCGGCATGGACGAGCTGTACAAGCTGCAGGGCGGAGGAGGCAGCGGCGGAGGAGGCAGCGGCGGAGGAGGCAGCGCCTGCTCGCGATGCTAGAGGGCTCTGCCAGTGAGCAAGGGCGAGGAGCTGTTCACCGGGGTGGTGCCCATCCTGGTCGAGCTGGACGGCGACGTAAACGGCCACAAGTTCAGCGTGTCCGGCGAGGGCGAGGGCGATGCCACCTACGGCAAGCTGACCCTGAAGTTCATCTGCACCACCGGCAAGCTGCCCGTGCCCTGGCCCACCCTCGTGACCACCCTGACCTACGGCGTGCAGTGCTTCAGCCGCTACCCCGACCACATGAAGCAGCACGACTTCTTCAAGTCCGCCATGCCCGAAGGCTACGTCCAGGAGCGCACCATCTTCTTCAAGGACGAC -g GCGCCTGCTCGCGATGCTAG \
--name mcherry-TED-WT --output_folder /home/gaolab/Downloads/sequences/ --write_cleaned_report \
--place_report_in_output_folder --plot_window_size 20 -w 13 -wc -3

# mcherry-TED-corrected
CRISPResso -r1 /home/gaolab/Downloads/sequences/mcherry-TED-LDL11903_L1_1.fq.gz \
-r2 /home/gaolab/Downloads/sequences/mcherry-TED-LDL11903_L1_2.fq.gz \
-a GGACATCACCTCCCACAACGAGGACTACACCATCGTGGAACAGTACGAACGCGCCGAGGGCCGCCACTCCACCGGCGGCATGGACGAGCTGTACAAGCTGCAGGGCGGAGGAGGCAGCGGCGGAGGAGGCAGCGGCGGAGGAGGCAGCGCCTGCTCGCGATGCTTGAGTGCTCTGCCAGTGAGCAAGGGCGAGGAGCTGTTCACCGGGGTGGTGCCCATCCTGGTCGAGCTGGACGGCGACGTAAACGGCCACAAGTTCAGCGTGTCCGGCGAGGGCGAGGGCGATGCCACCTACGGCAAGCTGACCCTGAAGTTCATCTGCACCACCGGCAAGCTGCCCGTGCCCTGGCCCACCCTCGTGACCACCCTGACCTACGGCGTGCAGTGCTTCAGCCGCTACCCCGACCACATGAAGCAGCACGACTTCTTCAAGTCCGCCATGCCCGAAGGCTACGTCCAGGAGCGCACCATCTTCTTCAAGGACGAC -g GCGCCTGCTCGCGATGCTTG \
--name mcherry-TED-corrected --output_folder /home/gaolab/Downloads/sequences/ --write_cleaned_report \
--place_report_in_output_folder --plot_window_size 20 -w 13 -wc -3

# G40-WT
CRISPResso -r1 /home/gaolab/Downloads/sequence2/N2114965_80-819200427_Delivery202112241216/00_RawData/G40_combined_R1.fastq.gz \
-r2 /home/gaolab/Downloads/sequence2/N2114965_80-819200427_Delivery202112241216/00_RawData/G40_combined_R2.fastq.gz \
-a ggcaaccgctacccacctcagggcggtggtggctgggggcagcctcatggtggtggctgggggcagcctcatggtggtggctgggggcagccccatggtggtggctggggacagcctcatggtggtggctggggtcaaggaggtggcacccacagtcagtggaacaagccgagtaagccaaaaaccaacatgaagcacatggctggtgctgcagcagctggggcagtggtggggggccttggcggctacatgctgggaagtgccatgagcaggcccatcatacatttcggcagtgactatgaggaccgttactatcgtgaaaacatgcaccgttaccccaaccaagtgtactacaggcccatggatgagtacagcaaccagaacaactttgtgcacgactgcgtcaatatcacaatcaagcagcacacggtcaccacaaccaccaagggggagaacttc \
-g gcagtggtggggggccttgg \
--name G40-WT --output_folder /home/gaolab/Downloads/sequence2/ --write_cleaned_report \
--place_report_in_output_folder --plot_window_size 10 -p 30

# G40-corrected
CRISPResso -r1 /home/gaolab/Downloads/sequence2/N2114965_80-819200427_Delivery202112241216/00_RawData/G40_combined_R1.fastq.gz \
-r2 /home/gaolab/Downloads/sequence2/N2114965_80-819200427_Delivery202112241216/00_RawData/G40_combined_R2.fastq.gz \
-a ggcaaccgctacccacctcagggcggtggtggctgggggcagcctcatggtggtggctgggggcagcctcatggtggtggctgggggcagccccatggtggtggctggggacagcctcatggtggtggctggggtcaaggaggtggcacccacagtcagtggaacaagccgagtaagccaaaaaccaacatgaagcacatggctggtgctgcagcagctggggcagtggtggggggccttggcgtctacatgctgggaagtgccatgagcaggcccatcatacatttcggcagtgactatgaggaccgttactatcgtgaaaacatgcaccgttaccccaaccaagtgtactacaggcccatggatgagtacagcaaccagaacaactttgtgcacgactgcgtcaatatcacaatcaagcagcacacggtcaccacaaccaccaagggggagaacttc \
-g gcagtggtggggggccttgg \
--name G40-corrected --output_folder /home/gaolab/Downloads/sequence2/ --write_cleaned_report \
--place_report_in_output_folder --plot_window_size 10 -p 30

# G41-WT
CRISPResso -r1 /home/gaolab/Downloads/sequence2/N2114965_80-819200427_Delivery202112241216/00_RawData/G41_combined_R1.fastq.gz \
-r2 /home/gaolab/Downloads/sequence2/N2114965_80-819200427_Delivery202112241216/00_RawData/G41_combined_R2.fastq.gz \
-a ggcaaccgctacccacctcagggcggtggtggctgggggcagcctcatggtggtggctgggggcagcctcatggtggtggctgggggcagccccatggtggtggctggggacagcctcatggtggtggctggggtcaaggaggtggcacccacagtcagtggaacaagccgagtaagccaaaaaccaacatgaagcacatggctggtgctgcagcagctggggcagtggtggggggccttggcggctacatgctgggaagtgccatgagcaggcccatcatacatttcggcagtgactatgaggaccgttactatcgtgaaaacatgcaccgttaccccaaccaagtgtactacaggcccatggatgagtacagcaaccagaacaactttgtgcacgactgcgtcaatatcacaatcaagcagcacacggtcaccacaaccaccaagggggagaacttc \
-g gcagtggtggggggccttgg \
--name G41-WT --output_folder /home/gaolab/Downloads/sequence2/ --write_cleaned_report \
--place_report_in_output_folder --plot_window_size 10 -p 30

# G41-corrected
CRISPResso -r1 /home/gaolab/Downloads/sequence2/N2114965_80-819200427_Delivery202112241216/00_RawData/G41_combined_R1.fastq.gz \
-r2 /home/gaolab/Downloads/sequence2/N2114965_80-819200427_Delivery202112241216/00_RawData/G41_combined_R2.fastq.gz \
-a ggcaaccgctacccacctcagggcggtggtggctgggggcagcctcatggtggtggctgggggcagcctcatggtggtggctgggggcagccccatggtggtggctggggacagcctcatggtggtggctggggtcaaggaggtggcacccacagtcagtggaacaagccgagtaagccaaaaaccaacatgaagcacatggctggtgctgcagcagctggggcagtggtggggggccttggcgtctacatgctgggaagtgccatgagcaggcccatcatacatttcggcagtgactatgaggaccgttactatcgtgaaaacatgcaccgttaccccaaccaagtgtactacaggcccatggatgagtacagcaaccagaacaactttgtgcacgactgcgtcaatatcacaatcaagcagcacacggtcaccacaaccaccaagggggagaacttc \
-g gcagtggtggggggccttgg \
--name G41-corrected --output_folder /home/gaolab/Downloads/sequence2/ --write_cleaned_report \
--place_report_in_output_folder --plot_window_size 10 -p 30

# G50-WT
CRISPResso -r1 /home/gaolab/Downloads/sequence2/N2114965_80-819200427_Delivery202112241216/00_RawData/G50_combined_R1.fastq.gz \
-r2 /home/gaolab/Downloads/sequence2/N2114965_80-819200427_Delivery202112241216/00_RawData/G50_combined_R2.fastq.gz \
-a GGACATCACCTCCCACAACGAGGACTACACCATCGTGGAACAGTACGAACGCGCCGAGGGCCGCCACTCCACCGGCGGCATGGACGAGCTGTACAAGCTGCAGGGCGGAGGAGGCAGCGGCGGAGGAGGCAGCGGCGGAGGAGGCAGCGCCTGCTCGCGATGCTAGAGGGCTCTGCCAGTGAGCAAGGGCGAGGAGCTGTTCACCGGGGTGGTGCCCATCCTGGTCGAGCTGGACGGCGACGTAAACGGCCACAAGTTCAGCGTGTCCGGCGAGGGCGAGGGCGATGCCACCTACGGCAAGCTGACCCTGAAGTTCATCTGCACCACCGGCAAGCTGCCCGTGCCCTGGCCCACCCTCGTGACCACCCTGACCTACGGCGTGCAGTGCTTCAGCCGCTACCCCGACCACATGAAGCAGCACGACTTCTTCAAGTCCGCCATGCCCGAAGGCTACGTCCAGGAGCGCACCATCTTCTTCAAGGACGAC \
-g GCGCCTGCTCGCGATGCTAG \
--name G50-WT --output_folder /home/gaolab/Downloads/sequence2/ --write_cleaned_report \
--place_report_in_output_folder --plot_window_size 10 -p 30

# G50-corrected
CRISPResso -r1 /home/gaolab/Downloads/sequence2/N2114965_80-819200427_Delivery202112241216/00_RawData/G50_combined_R1.fastq.gz \
-r2 /home/gaolab/Downloads/sequence2/N2114965_80-819200427_Delivery202112241216/00_RawData/G50_combined_R2.fastq.gz \
-a GGACATCACCTCCCACAACGAGGACTACACCATCGTGGAACAGTACGAACGCGCCGAGGGCCGCCACTCCACCGGCGGCATGGACGAGCTGTACAAGCTGCAGGGCGGAGGAGGCAGCGGCGGAGGAGGCAGCGGCGGAGGAGGCAGCGCCTGCTCGCGATGCTtGAGtGCTCTGCCAGTGAGCAAGGGCGAGGAGCTGTTCACCGGGGTGGTGCCCATCCTGGTCGAGCTGGACGGCGACGTAAACGGCCACAAGTTCAGCGTGTCCGGCGAGGGCGAGGGCGATGCCACCTACGGCAAGCTGACCCTGAAGTTCATCTGCACCACCGGCAAGCTGCCCGTGCCCTGGCCCACCCTCGTGACCACCCTGACCTACGGCGTGCAGTGCTTCAGCCGCTACCCCGACCACATGAAGCAGCACGACTTCTTCAAGTCCGCCATGCCCGAAGGCTACGTCCAGGAGCGCACCATCTTCTTCAAGGACGAC \
-g GCGCCTGCTCGCGATGCTTG \
--name G50-corrected --output_folder /home/gaolab/Downloads/sequence2/ --write_cleaned_report \
--place_report_in_output_folder --plot_window_size 10 -p 30
